export const SETUP_ROLES = [
  { label: "DevOps", value: "devops" },
  { label: "프론트엔드 개발", value: "frontend" },
  { label: "백엔드 개발", value: "backend" },
  { label: "Android 개발", value: "android" },
  { label: "iOS 개발", value: "ios" },
  { label: "빅데이터 엔지니어", value: "bigdata" },
  { label: "인공지능 · 머신러닝", value: "ai-ml" },
  { label: "응용 SW 개발", value: "application" },
  { label: "게임 클라이언트 개발", value: "game-client" },
  { label: "게임 서버 개발", value: "game-server" },
  { label: "크로스플랫폼 앱 개발", value: "cross-platform" },
  { label: "VR/AR 엔지니어", value: "vr-ar" },
  { label: "그래픽스 엔지니어", value: "graphics" },
  { label: "시스템 네트워크 엔지니어", value: "system-network" },
  { label: "블록체인 개발", value: "blockchain" },
  { label: "SW 엔지니어", value: "software" },
  { label: "임베디드 · 하드웨어", value: "embedded" },
];
